defaults:
  - common

_target_: envs.GuardedMazeCeSoR

mode: 1
action_noise: 0.2
guard_prob: 0.05
guard_cost: 4
rand_guard: False
rand_cost: False
detailed_r: False
force_motion: 0
collect: False
fixed_reset: True
init_state: [1, 1]
continuous: True
deduction_limit: 32